POS/Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Model;

namespace POS.Controllers
{
    public class AdministradorController : Controller
    {
        private POSDataContext db = new POSDataContext();
        // GET: Administrador
        public ActionResult Index()
        {
            var q = db.MENUs.ToList();   
            return View(q);
        }
        
        [HttpGet]
        public ActionResult Mantenimentos(string page) {
            string pages = "../" + page;
            return Redirect(page);
            //return View(page);        
        }
    }
}

POS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Model;


namespace POS.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        
        public ActionResult Index()
        {
            string page = "Login";
            return View(page);
        }

    [HttpPost]
    public ActionResult Index(USUARIO usr)
    {
            string page = "Login";
            var db = new POSDataContext();
            var q  = db.USUARIOs.Where(u =>  u.clave.Equals(usr.clave) && u.usuario1.Equals(usr.usuario1)).SingleOrDefault();


            if (q == null)
            {
                ViewBag.errorMessage = "Usuario O Clave invalido";                
                page = "Login";
            }
            else {
                page = q.ROL1.nombre;
            }

        return View();
    }

}
}

POS/Controllers/MenuController.cs
using POS.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POS.Controllers
{
    public class MenuController : Controller
    {
        private POSDataContext db = new POSDataContext();

        // GET: Menu
        public ActionResult Index()
        {
            List<MENU> menus = db.MENUs.ToList();
            return View(menus);
        }

        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(MENU m)
        {
            db.MENUs.InsertOnSubmit(m);
            db.SubmitChanges();
            return Redirect("Index");
        }

        [HttpGet]
        public ActionResult Editar(string id)
        {            
            MENU menu = db.MENUs.Where( m => m.idMenu == int.Parse( id)).Single();
            return View(menu);
        }

        [HttpPost]
        public ActionResult Editar(MENU m)
        {
            db.MENUs.GetModifiedMembers(m);
            db.SubmitChanges();
            return Redirect("Index");
        }

    }
}

POS/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Model;

namespace POS.Controllers
{
    public class RolController : Controller
    {
        private POSDataContext db = new POSDataContext();

        // GET: Menu
        public ActionResult Index()
        {
            List<ROL> rol = db.ROLs.ToList();
            return View(rol);
        }

        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(ROL m)
        {
            db.ROLs.InsertOnSubmit(m);
            db.SubmitChanges();
            return Redirect("Index");
        }

        [HttpGet]
        public ActionResult Editar(int? id)
        {
            ROL u = db.ROLs.Where(m => m.idRol ==id).Single();
            return View(u);
        }

        [HttpPost]
        public ActionResult Editar(ROL m)
        {
            db.ROLs.GetModifiedMembers(m);
            db.SubmitChanges();
            return Redirect("Index");
        }
    }

}

POS/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Model;
namespace POS.Controllers
{
    public class UsuarioController : Controller
    {
        private POSDataContext db = new POSDataContext();

        // GET: Menu
        public ActionResult Index()
        {
            List<USUARIO> menus = db.USUARIOs.ToList();
            return View(menus);
        }

        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(USUARIO m)
        {
            db.USUARIOs.InsertOnSubmit(m);
            db.SubmitChanges();
            return Redirect("Index");
        }

        [HttpGet]
        public ActionResult Editar(string id)
        {
            USUARIO u = db.USUARIOs.Where(m => m.DUI.Equals(id)).Single();
            return View(u);
        }

        [HttpPost]
        public ActionResult Editar(USUARIO m)
        {
            db.USUARIOs.GetModifiedMembers(m);
            db.SubmitChanges();
            return Redirect("Index");
        }
    }
}

POS/Views/Administrador/Index.cshtml
@model IEnumerable<POS.Model.MENU>

@using POS.Model;
@{
    ViewBag.Title = "Administrador";
}

<div class="container">
    <div class="col-6 col-md-4">
        <div class="dropdown-menu">

            @foreach (MENU m in @Model)
            {
                <li>
                    @Html.ActionLink(m.pagina, "Mantenimentos", new { id = m.pagina })
                </li>
            }

        </div>
        </div>
        <div class="col-6 col-md-4"></div>
    </div>

POS/Views/Administrador/Mantenimentos.cshtml
@using POS.Model;
@model IEnumerable<POS.Model.MENU>

@{
    ViewBag.Title = "MtoMenu";
}

<h2>MtoMenu</h2>

<div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Descipcion</th>
                <th>Activo</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (MENU m in @Model)
            {

                <tr>
                    <td>@m.idMenu</td>
                    <td>@m.pagina</td>
                    <td>@m.descripcion</td>
                    <td>@m.activo</td>
                    <td>@Html.ActionLink("Editar", "edit", new { id = m.idMenu})</td>
                </tr>
            }
        </tbody>
    </table>
</div>

POS/Views/Administrador/MtoMenu.cshtml
@using POS.Model;
@model IEnumerable<POS.Model.MENU>

@{
    ViewBag.Title = "MtoMenu";
}

<h2>MtoMenu</h2>

<div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Descipcion</th>
                <th>Activo</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (MENU m in @Model)
            {

                <tr>
                    <td>@m.idMenu</td>
                    <td>@m.pagina</td>
                    <td>@m.descripcion</td>
                    <td>@m.activo</td>
                    <td>@Html.ActionLink("Editar", "edit", new { id = m.idMenu })</td>
                </tr>
            }
        </tbody>
    </table>
</div>

POS/Views/Home/Login.cshtml
@model POS.Model.USUARIO

@{
    ViewBag.Title = "Login";
}

<fieldset style="margin:auto; width:35%; border:1px solid groove;">
    <legend>Ingreso</legend>
    @using (Html.BeginForm("Index", "Home", FormMethod.Post))
    {
        <table>
            <tr>
                <td colspan="3">
                   @ViewBag.errorMessage
                </td>
            </tr>
            <tr>
                <td>Usuario</td>
                <td>@Html.TextBoxFor(usr => usr.usuario1)</td>
                <td></td>
            </tr>
            <tr>
                <td>Clave</td>
                <td>@Html.PasswordFor(usr => usr.clave)</td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Ingresar" /></td>
                <td></td>
            </tr>

        </table>
    }
</fieldset>

POS/Views/Menu/Editar.cshtml
@model POS.Model.MENU

@{
    ViewBag.Title = "Nuevo";
}


@using (Html.BeginForm("Nuevo", "Menu", FormMethod.Post))
{
    <h2>Modificar registro</h2>

    <table>
        <tr>
            <td>ID</td>
            <td>@Html.TextBoxFor(m => m.idMenu)</td>
        </tr>
        <tr>
            <td>Nombre</td>
            <td>@Html.TextBoxFor(m => m.pagina)</td>
        </tr>
        <tr>
            <td>Descipcion</td>
            <td>@Html.TextBoxFor(m => m.descripcion)</td>
        </tr>
        <tr>
            <td>Activo</td>
            <td>@Html.TextBoxFor(m => m.activo)</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary"/></td>
        </tr>
    </table>
}

POS/Views/Menu/Index.cshtml
@using POS.Model;
@model IEnumerable<POS.Model.MENU>


@{
    ViewBag.Title = "Mantenimeinto de Menus";
}

<h2>MtoMenu</h2>

<div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descipcion</th>
                <th scope="col">Activo</th>
                <th scope="col">@Html.ActionLink("Nuevo", "Nuevo",null, new { @class = "btn btn-primary" })</th>
            </tr>
        </thead>

        <tbody>
            @foreach (MENU m in @Model)
            {

            <tr scope="row">
                <td>@m.idMenu</td>
                <td>@m.pagina</td>
                <td>@m.descripcion</td>
                <td>@m.activo</td>
                <!--<td>@Html.ActionLink("Editar", "Editar", new { id = m.idMenu })</td>-->
            </tr>
            }
        </tbody>
    </table>
</div>

POS/Views/Menu/Nuevo.cshtml
@model POS.Model.MENU

@{
    ViewBag.Title = "Nuevo";
}


@using (Html.BeginForm("Nuevo", "Menu", FormMethod.Post))
{
<table>
    <tr>
        <td>ID</td>
        <td></td>
    </tr>
    <tr>
        <td>Nombre</td>
        <td>@Html.TextBoxFor(m => m.pagina)</td>
    </tr>
    <tr>
        <td>Descipcion</td>
        <td>@Html.TextBoxFor(m => m.descripcion)</td>
    </tr>
    <tr>
        <td>Activo</td>
        <td>@Html.TextBoxFor(m => m.activo)</td>
    </tr>
    <tr>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td><input type="submit" value="Guardar Nuevo" /></td>
    </tr>
</table>
}

POS/Views/Rol/Editar.cshtml
@model POS.Model.ROL

@{
    ViewBag.Title = "Nuevo";
}


@using (Html.BeginForm("Nuevo", "Rol", FormMethod.Post))
{
    <h2>Modificar registro</h2>

    <table>
        <tr>
            <td>ID</td>
            <td>@Html.TextBoxFor(m => m.idRol)</td>
        </tr>
        <tr>
            <td>Nombre</td>
            <td>@Html.TextBoxFor(m => m.nombre)</td>
        </tr>
        <tr>
            <td>Descipcion</td>
            <td>@Html.TextBoxFor(m => m.decripcion)</td>
        </tr>
        <tr>
            <td>Activo</td>
            <td>@Html.CheckBoxFor(m => m.activo.Value)</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary"/></td>
        </tr>
    </table>
}

POS/Views/Rol/Index.cshtml
@using POS.Model;
@model IEnumerable<POS.Model.ROL>


@{
    ViewBag.Title = "Mantenimeinto de Roles";
}

<h2>Mantenimiento Roles</h2>

<div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descipcion</th>
                <th scope="col">Activo</th>
                <th scope="col">@Html.ActionLink("Nuevo", "Nuevo",null, new { @class = "btn btn-primary" })</th>
            </tr>
        </thead>

        <tbody>
            @foreach (ROL m in @Model)
            {

            <tr scope="row">
                <td>@m.idRol</td>
                <td>@m.nombre</td>
                <td>@m.decripcion</td>
                <td>@m.activo</td>
                <!--<td>@Html.ActionLink("Editar", "Editar", new { id = m.idRol })</td>-->
            </tr>
            }
        </tbody>
    </table>
</div>

POS/Views/Rol/Nuevo.cshtml
@model POS.Model.ROL

@{
    ViewBag.Title = "Nuevo";
}


@using (Html.BeginForm("Nuevo", "Rol", FormMethod.Post))
{
    <h2>Nuevo registro para Menu</h2>

    <table>
        <tr>
            <td>ID</td>
            <td></td>
        </tr>
        <tr>
            <td>Nombre</td>
            <td>@Html.TextBoxFor(m => m.nombre)</td>
        </tr>
        <tr>
            <td>Descipcion</td>
            <td>@Html.TextBoxFor(m => m.decripcion)</td>
        </tr>
        <tr>
            <td>Activo</td>
            <td>@Html.TextBoxFor(m => m.activo)</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary"/></td>
        </tr>
    </table>
}

POS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Punto de venta", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Punto de venta</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

POS/Views/Usuario/Editar.cshtml
@model POS.Model.USUARIO

@{
    ViewBag.Title = "Nuevo";
}


@using (Html.BeginForm("Nuevo", "Usuario", FormMethod.Post))
{
    <h2>Modificar registro</h2>

    <table>
        <tr>
            <td>ID</td>
            <td>@Html.TextBoxFor(m => m.DUI)</td>
        </tr>
        <tr>
            <td>Nombre</td>
            <td>@Html.TextBoxFor(m => m.nombre)</td>
        </tr>
        <tr>
            <td>Descipcion</td>
            <td>@Html.TextBoxFor(m => m.sexo)</td>
        </tr>
        <tr>
            <td>Activo</td>
            <td>@Html.TextBoxFor(m => m.activo)</td>
        </tr>
        <tr>
            <td>Clave</td>
            <td>@Html.TextBoxFor(m => m.clave)</td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.TextBoxFor(m => m.ROL1.nombre)</td>
        </tr>
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary" /></td>
        </tr>
    </table>
}

POS/Views/Usuario/Index.cshtml
@using POS.Model;
@model IEnumerable<POS.Model.USUARIO>


@{
    ViewBag.Title = "Mantenimeinto de Menus";
}

<h2>MtoMenu</h2>

<div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">DUI</th>
                <th scope="col">Nombre</th>
                <th scope="col">Rol</th>
                <th scope="col">Activo</th>
                <th scope="col">@Html.ActionLink("Nuevo", "Nuevo",null, new { @class = "btn btn-primary" })</th>
            </tr>
        </thead>

        <tbody>
            @foreach (USUARIO m in @Model)
            {

            <tr scope="row">
                <td>@m.DUI</td>
                <td>@m.nombre</td>
                <td>@m.ROL1.nombre</td>
                <td>@m.activo</td>
                <!--<td>@Html.ActionLink("Editar", "Editar", new { id = m.DUI })</td>-->
            </tr>
            }
        </tbody>
    </table>
</div>

POS/Views/Usuario/Nuevo.cshtml
@model POS.Model.USUARIO

@{
    ViewBag.Title = "Nuevo";
}


@using (Html.BeginForm("Nuevo", "Usuario", FormMethod.Post))
{
    <h2>Nuevo registro para Menu</h2>

    <table>
        <tr>
            <td>ID</td>
            <td>@Html.TextBoxFor(m => m.DUI)</td>
        </tr>
        <tr>
            <td>Nombre</td>
            <td>@Html.TextBoxFor(m => m.nombre)</td>
        </tr>
        <tr>
            <td>Sexo</td>
            <td>
                @Html.RadioButtonFor(m => m.sexo, "M" ) M
                @Html.RadioButtonFor(m => m.sexo, "F" ) F
            </td>
        </tr>
        <tr>
            <td>Activo</td>
            <td>@Html.TextBoxFor(m => m.activo)</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary"/></td>
        </tr>
    </table>
}